# Generated by Django 3.2.25 on 2025-07-28 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_feedback_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('categoria', models.CharField(max_length=100)),
                ('nota', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EdicaoCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas_ac', models.IntegerField(default=0)),
                ('vagas_ppi_br', models.IntegerField(default=0)),
                ('vagas_publica_br', models.IntegerField(default=0)),
                ('vagas_ppi_publica', models.IntegerField(default=0)),
                ('vagas_publica', models.IntegerField(default=0)),
                ('vagas_deficientes', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.curso')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.edicao')),
            ],
        ),
        migrations.DeleteModel(
            name='DemoModel',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AddField(
            model_name='candidato',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.curso'),
        ),
    ]
